# Generated by Django 4.1 on 2022-08-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
